name: publish

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: fetch code
        uses: actions/checkout@v2

      - name: setup pages
        id: pages
        uses: actions/configure-pages@v1

      - name: set python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install node dependencies
        run: pip install -r requirements.txt

      - name: build
        run: lektor build --output-path ./build

      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v1